#spring:
#  application:
#    name: demo-spring-boot-mybatis-plus
#  profiles:
#    active: dev
##mybatis
#mybatis-plus:
#  # xml
#  mapper-locations: classpath:mapper/*Mapper.xml
#  # 实体扫描，多个package用逗号或者分号分隔
#  type-aliases-package: com.jason
#  global-config:
#    #刷新mapper 调试神器
#    db-config:
#      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#      id-type: assign_id
#      #逻辑删除配置
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#
#knife4j:
#  enable: true
#  # 开启生产环境屏蔽  true 关闭swagger   false 开启swagger
#  production: false
#
#  #开启swagger访问需要密码配置
##  basic:
##      enable: true
##      # Basic认证用户名
##      username: test
##      # Basic认证密码
##      password: 123
#
#
#
